spring:
  datasource:
    url: jdbc:h2:mem:~/foodWalletApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    com.foodwallet.server: debug

jwt:
  secret: ${jwt.secret}

cloud:
  aws:
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}
    s3:
      bucket: food-wallet
    stack:
      auto: false
    region:
      static: ap-northeast-2

